import { APIs } from "../../interfaces/APIs";
import { Endpoints } from "../../interfaces/Endpoint";

export const ApiData: APIs[] = [
  {
    id: 1,
    endpoint: "/users",
    method: "GET",
    description: "Retrieve user list",
    headers: [],
    parameters: [],
    payload: [],
    // enabled: true,
    // responseTime: "350ms",
    status: "Success",
    created_at: "2024-09-19T10:30:00Z",
    // timeStamp: "2024-09-19T10:30:00Z",
    // fullUrls: "",
  },
  // {
  //   id: 2,
  //   endpoint: "/users",
  //   method: "POST",
  //   description: "Create a new user",
  //   headers: [],
  //   payload: {
  //     name: "John Doe",
  //     email: "john@example.com",
  //   },
  //   enabled: true,
  //   responseTime: "420ms",
  //   status: "Failed",
  //   timeStamp: "2024-09-19T11:00:00Z",
  //   fullUrls: "",
  // },
  // {
  //   id: 3,
  //   endpoint: "/users/{id}",
  //   method: "PUT",
  //   description: "Update user information",
  //   headers: [],
  //   payload: {
  //     name: "Jane Doe",
  //   },
  //   queries: [],
  //   enabled: false,
  //   responseTime: "500ms",
  //   status: "Success",
  //   timeStamp: "2024-09-19T11:30:00Z",
  //   fullUrls: "",
  // },
  // {
  //   id: 4,
  //   endpoint: "/users/{id}",
  //   method: "GET",
  //   description: "Get a user",
  //   headers: [],
  //   payload: {},
  //   enabled: true,
  //   responseTime: "350ms",
  //   status: "Success",
  //   timeStamp: "2024-09-19T10:30:00Z",
  //   fullUrls: "",
  // },
  // {
  //   id: 5,
  //   endpoint: "/products",
  //   method: "GET",
  //   description: "Retrieve product list",
  //   headers: [],
  //   payload: {},
  //   parameters: {
  //     limit: 20,
  //     offset: 0,
  //   },
  //   enabled: true,
  //   responseTime: "420ms",
  //   status: "Failed",
  //   timeStamp: "2024-09-19T11:00:00Z",
  //   fullUrls: "",
  // },
  // {
  //   id: 6,
  //   endpoint: "/products",
  //   method: "POST",
  //   description: "Add a new product",
  //   headers: [],
  //   payload: {
  //     name: "Product 1",
  //     price: 50,
  //   },
  //   parameters: {},
  //   enabled: true,
  //   responseTime: "500ms",
  //   status: "Success",
  //   timeStamp: "2024-09-19T11:30:00Z",
  //   fullUrls: "",
  // },
  // {
  //   id: 7,
  //   endpoint: "/orders",
  //   method: "GET",
  //   description: "Retrieve order list",
  //   headers: [],
  //   payload: {},
  //   parameters: {
  //     limit: 15,
  //     offset: 0,
  //   },
  //   enabled: true,
  //   responseTime: "350ms",
  //   status: "Success",
  //   timeStamp: "2024-09-19T10:30:00Z",
  //   fullUrls: "",
  // },
  // {
  //   id: 8,
  //   endpoint: "/orders/{id}",
  //   method: "PATCH",
  //   description: "Update order status",
  //   headers: [],
  //   payload: {
  //     status: "shipped",
  //     id: 101,
  //   },
  //   parameters: {},
  //   enabled: true,
  //   responseTime: "420ms",
  //   status: "Failed",
  //   timeStamp: "2024-09-19T11:00:00Z",
  //   fullUrls: "",
  // },
  // {
  //   id: 9,
  //   endpoint: "/orders/{id}",
  //   method: "DELETE",
  //   description: "Delete an order",
  //   headers: [],
  //   payload: {},
  //   parameters: {},
  //   enabled: false,
  //   responseTime: "500ms",
  //   status: "Success",
  //   timeStamp: "2024-09-19T11:30:00Z",
  //   fullUrls: "",
  // },
  // {
  //   id: 10,
  //   endpoint: "/categories",
  //   method: "GET",
  //   description: "Retrieve category list",
  //   headers: [],
  //   payload: {},
  //   parameters: {
  //     limit: 5,
  //   },
  //   enabled: true,
  //   responseTime: "480ms",
  //   status: "Success",
  //   timeStamp: "2024-09-19T11:30:00Z",
  //   fullUrls: "",
  // },
];
