import { Notification } from "../../../interfaces/Notification";

export const notificationsData: Notification[] = [
  {
    id: 1,
    message: "System maintenance scheduled for midnight.",
    type: "Info",
    recipients: ["Admin", "Developer"],
    deliveryMethod: "Email",
    status: "Sent",
    timestamp: "2024-09-19T10:00:00Z",
  },
  {
    id: 2,
    message: "API performance degradation detected.",
    type: "Critical",
    recipients: ["Admin"],
    deliveryMethod: "SMS",
    status: "Pending",
    timestamp: "2024-09-19T12:00:00Z",
  },
  {
    id: 3,
    message: "Your API call limit has been exceeded.",
    type: "Warning",
    recipients: ["Developer", "Admin"],
    deliveryMethod: "In-app",
    status: "Sent",
    timestamp: "2024-09-19T14:00:00Z",
  },
  {
    id: 4,
    message: "System maintenance scheduled for midnight.",
    type: "Info",
    recipients: ["Admin", "Developer"],
    deliveryMethod: "Email",
    status: "Sent",
    timestamp: "2024-09-19T10:00:00Z",
  },
  {
    id: 5,
    message: "API performance degradation detected.",
    type: "Critical",
    recipients: ["Admin"],
    deliveryMethod: "SMS",
    status: "Pending",
    timestamp: "2024-09-19T12:00:00Z",
  },
  {
    id: 6,
    message: "Your API call limit has been exceeded.",
    type: "Warning",
    recipients: ["Developer", "Admin"],
    deliveryMethod: "In-app",
    status: "Sent",
    timestamp: "2024-09-19T14:00:00Z",
  },
  {
    id: 7,
    message: "System maintenance scheduled for midnight.",
    type: "Info",
    recipients: ["Admin", "Developer"],
    deliveryMethod: "Email",
    status: "Sent",
    timestamp: "2024-09-19T10:00:00Z",
  },
  {
    id: 8,
    message: "API performance degradation detected.",
    type: "Critical",
    recipients: ["Admin"],
    deliveryMethod: "SMS",
    status: "Pending",
    timestamp: "2024-09-19T12:00:00Z",
  },
  {
    id: 9,
    message: "Your API call limit has been exceeded.",
    type: "Warning",
    recipients: ["Developer", "Admin"],
    deliveryMethod: "In-app",
    status: "Sent",
    timestamp: "2024-09-19T14:00:00Z",
  },
  {
    id: 10,
    message: "System maintenance scheduled for midnight.",
    type: "Info",
    recipients: ["Admin", "Developer"],
    deliveryMethod: "Email",
    status: "Sent",
    timestamp: "2024-09-19T10:00:00Z",
  },
  {
    id: 11,
    message: "API performance degradation detected.",
    type: "Critical",
    recipients: ["Admin"],
    deliveryMethod: "SMS",
    status: "Pending",
    timestamp: "2024-09-19T12:00:00Z",
  },
  {
    id: 12,
    message: "Your API call limit has been exceeded.",
    type: "Warning",
    recipients: ["Developer", "Admin"],
    deliveryMethod: "In-app",
    status: "Sent",
    timestamp: "2024-09-19T14:00:00Z",
  },
];
