import { Audit } from "../../../interfaces/Audit";

export const auditData: Audit[] = [
  {
    id: 1,
    actionType: "Create",
    user: "Admin",
    targetResource: "API Endpoint",
    dateTime: "2024-09-19T10:00:00Z",
    ipAddress: "192.168.1.10",
    status: "Success",
    details: "Created new API endpoint for user authentication.",
  },
  {
    id: 2,
    actionType: "Update",
    user: "Developer",
    targetResource: "API Key",
    dateTime: "2024-09-19T12:00:00Z",
    ipAddress: "192.168.1.15",
    status: "Success",
    details: "Updated API key expiration for API calls.",
  },
  {
    id: 3,
    actionType: "Delete",
    user: "Admin",
    targetResource: "User",
    dateTime: "2024-09-19T14:00:00Z",
    ipAddress: "192.168.1.20",
    status: "Failure",
    details: "Attempted to delete user account but operation failed.",
  },
  {
    id: 4,
    actionType: "Create",
    user: "Admin",
    targetResource: "API Endpoint",
    dateTime: "2024-09-19T10:00:00Z",
    ipAddress: "192.168.1.10",
    status: "Success",
    details: "Created new API endpoint for user authentication.",
  },
  {
    id: 5,
    actionType: "Update",
    user: "Developer",
    targetResource: "API Key",
    dateTime: "2024-09-19T12:00:00Z",
    ipAddress: "192.168.1.15",
    status: "Success",
    details: "Updated API key expiration for API calls.",
  },
  {
    id: 6,
    actionType: "Delete",
    user: "Admin",
    targetResource: "User",
    dateTime: "2024-09-19T14:00:00Z",
    ipAddress: "192.168.1.20",
    status: "Failure",
    details: "Attempted to delete user account but operation failed.",
  },
  {
    id: 7,
    actionType: "Create",
    user: "Admin",
    targetResource: "API Endpoint",
    dateTime: "2024-09-19T10:00:00Z",
    ipAddress: "192.168.1.10",
    status: "Success",
    details: "Created new API endpoint for user authentication.",
  },
  {
    id: 8,
    actionType: "Update",
    user: "Developer",
    targetResource: "API Key",
    dateTime: "2024-09-19T12:00:00Z",
    ipAddress: "192.168.1.15",
    status: "Success",
    details: "Updated API key expiration for API calls.",
  },
  {
    id: 9,
    actionType: "Delete",
    user: "Admin",
    targetResource: "User",
    dateTime: "2024-09-19T14:00:00Z",
    ipAddress: "192.168.1.20",
    status: "Failure",
    details: "Attempted to delete user account but operation failed.",
  },
  {
    id: 10,
    actionType: "Create",
    user: "Admin",
    targetResource: "API Endpoint",
    dateTime: "2024-09-19T10:00:00Z",
    ipAddress: "192.168.1.10",
    status: "Success",
    details: "Created new API endpoint for user authentication.",
  },
  {
    id: 11,
    actionType: "Update",
    user: "Developer",
    targetResource: "API Key",
    dateTime: "2024-09-19T12:00:00Z",
    ipAddress: "192.168.1.15",
    status: "Success",
    details: "Updated API key expiration for API calls.",
  },
  {
    id: 12,
    actionType: "Delete",
    user: "Admin",
    targetResource: "User",
    dateTime: "2024-09-19T14:00:00Z",
    ipAddress: "192.168.1.20",
    status: "Failure",
    details: "Attempted to delete user account but operation failed.",
  },
];
