import { HeaderProps } from "../interfaces/Headers";

export const HeadersData: HeaderProps[] = [
  {
    name: "Accept",
    description: "Specifies the type of data the client can handle",
    example: "Accept: text/html",
    category: "Request Header",
    samples: ["text/html", "application/json", "image/jpeg", "application/xml"],
  },
  {
    name: "Accept-Charset",
    description: "Specifies the character encoding the client can handle",
    example: "Accept-Charset: utf-8",
    category: "Request Header",
    samples: ["utf-8", "iso-8859-1", "windows-1252"],
  },
  {
    name: "Accept-Encoding",
    description: "Specifies the compression algorithm the client can handle",
    example: "Accept-Encoding: gzip",
    category: "Request Header",
    samples: ["gzip", "deflate", "br", "identity"],
  },
  {
    name: "Accept-Language",
    description: "Specifies the language the client prefers",
    example: "Accept-Language: en-US",
    category: "Request Header",
    samples: ["en-US", "fr-FR", "es-ES", "zh-CN"],
  },
  {
    name: "Authorization",
    description: "Provides authentication information",
    example: "Authorization: Bearer <token>",
    category: "Request Header",
    samples: [
      "Bearer 1234567890",
      "Basic QWxhZGpr",
      'Digest username="admin", realm="example", nonce="", response="", uri="", algorithm=MD5',
    ],
  },
  {
    name: "Cache-Control",
    description: "Specifies how the client and server handle caching",
    example: "Cache-Control: max-age=3600",
    category: "Request/Response Header",
    samples: ["max-age=3600", "no-cache", "no-store", "must-revalidate"],
  },
  {
    name: "Connection",
    description: "Specifies whether the connection should remain open",
    example: "Connection: keep-alive",
    category: "Request/Response Header",
    samples: ["keep-alive", "close"],
  },
  {
    name: "Content-Type",
    description: "Specifies the type of data being sent",
    example: "Content-Type: application/json",
    category: "Request/Response Header",
    samples: ["application/json", "text/html", "image/jpeg", "application/xml"],
  },
  {
    name: "Cookie",
    description: "Sends cookies to the server",
    example: "Cookie: session_id=123456",
    category: "Request Header",
    samples: ["session_id=123456", "username=admin", "lang=en-US"],
  },
  {
    name: "Date",
    description: "Specifies the date and time of the message",
    example: "Date: Wed, 21 Jan 2020 07:28:00 GMT",
    category: "General Header",
    samples: ["Wed, 21 Jan 2020 07:28:00 GMT", "Tue, 20 Jan 2020 14:30:00 PST"],
  },
  {
    name: "Expect",
    description: "Specifies the expected behavior of the server",
    example: "Expect: 100-continue",
    category: "Request Header",
    samples: ["100-continue"],
  },
  {
    name: "From",
    description: "Specifies the email address of the user",
    example: "From: user@(link unavailable)",
    category: "Request Header",
    samples: ["user@(link unavailable)"],
  },
  {
    name: "Host",
    description: "Specifies the domain name or IP address of the server",
    example: "Host: (link unavailable)",
    category: "Request Header",
    samples: ["(link unavailable)", "(link unavailable)", "192.0.2.1"],
  },
  {
    name: "If-Match",
    description: "Specifies the entity tag of the resource",
    example: 'If-Match: "1234567890"',
    category: "Request Header",
    samples: ['"1234567890"'],
  },
  {
    name: "If-Modified-Since",
    description: "Specifies the date and time of the last modification",
    example: "If-Modified-Since: Wed, 21 Jan 2020 07:28:00 GMT",
    category: "Request Header",
    samples: ["Wed, 21 Jan 2020 07:28:00 GMT", "Tue, 20 Jan 2020 14:30:00 PST"],
  },
  {
    name: "If-None-Match",
    description: "Specifies the entity tag of the resource",
    example: 'If-None-Match: "1234567890"',
    category: "Request Header",
    samples: ['"1234567890"'],
  },
  {
    name: "If-Range",
    description: "Specifies the range of the resource",
    example: 'If-Range: "1234567890"',
    category: "Request Header",
    samples: ['"1234567890"'],
  },
  {
    name: "If-Unmodified-Since",
    description: "Specifies the date and time of the last modification",
    example: "If-Unmodified-Since: Wed, 21 Jan 2020 07:28:00 GMT",
    category: "Request Header",
    samples: ["Wed, 21 Jan 2020 07:28:00 GMT", "Tue, 20 Jan 2020 14:30:00 PST"],
  },
  {
    name: "Max-Forwards",
    description: "Specifies the maximum number of forwards",
    example: "Max-Forwards: 10",
    category: "Request Header",
    samples: ["10"],
  },
  {
    name: "Origin",
    description: "Specifies the origin of the request",
    example: "Origin: (link unavailable)",
    category: "Request Header",
    samples: ["(link unavailable)", "http://(link unavailable)", "null"],
  },
  {
    name: "Pragma",
    description: "Specifies implementation-specific directives",
    example: "Pragma: no-cache",
    category: "General Header",
    samples: ["no-cache"],
  },
  {
    name: "Proxy-Authorization",
    description: "Provides authentication information for the proxy",
    example: "Proxy-Authorization: Basic QWxhZGpr",
    category: "Request Header",
    samples: ["Basic QWxhZGpr"],
  },
  {
    name: "Range",
    description: "Specifies the range of the resource",
    example: "Range: bytes=0-1023",
    category: "Request Header",
    samples: ["bytes=0-1023"],
  },
  {
    name: "Referer",
    description: "Specifies the URL of the referring page",
    example: "Referer: (link unavailable)",
    category: "Request Header",
    samples: ["(link unavailable)"],
  },
  {
    name: "TE",
    description: "Specifies the transfer encoding",
    example: "TE: trailers, chunked",
    category: "Request Header",
    samples: ["trailers, chunked"],
  },
  {
    name: "Trailer",
    description: "Specifies the trailers that will be sent",
    example: "Trailer: Foo",
    category: "General Header",
    samples: ["Foo"],
  },
  {
    name: "Transfer-Encoding",
    description: "Specifies the transfer encoding",
    example: "Transfer-Encoding: chunked",
    category: "General Header",
    samples: ["chunked"],
  },
  {
    name: "Upgrade",
    description: "Specifies the protocol upgrade",
    example: "Upgrade: websocket",
    category: "General Header",
    samples: ["websocket"],
  },
  {
    name: "User-Agent",
    description: "Specifies the client software and operating system",
    example: "User-Agent: Mozilla/5.0",
    category: "Request Header",
    samples: ["Mozilla/5.0", "Chrome/74.0.3729.169"],
  },
  {
    name: "Via",
    description: "Specifies the intermediate proxies",
    example: "Via: 1.1 (link unavailable)",
    category: "General Header",
    samples: ["1.1 (link unavailable)"],
  },
  {
    name: "Warning",
    description: "Specifies additional information about the response",
    example: "Warning: 199 - Miscellaneous warning",
    category: "General Header",
    samples: ["199 - Miscellaneous warning"],
  },
  {
    name: "WWW-Authenticate",
    description: "Specifies the authentication scheme",
    example: 'WWW-Authenticate: Basic realm="example"',
    category: "Response Header",
    samples: ['Basic realm="example"'],
  },
  {
    name: "X-Frame-Options",
    description: "Specifies the frame options",
    example: "X-Frame-Options: DENY",
    category: "Response Header",
    samples: ["DENY", "SAMEORIGIN"],
  },
  {
    name: "X-Content-Type-Options",
    description: "Specifies the content type options",
    example: "X-Content-Type-Options: nosniff",
    category: "Response Header",
    samples: ["nosniff"],
  },
  {
    name: "X-XSS-Protection",
    description: "Specifies the XSS protection",
    example: "X-XSS-Protection: 1; mode=block",
    category: "Response Header",
    samples: ["1; mode=block"],
  },
];
