import { User } from "../../../interfaces/User";

export const usersData: User[] = [
  {
    id: 1,
    fullName: "John Doe",
    email: "john.doe@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-09-19T12:34:00Z",
  },
  {
    id: 2,
    fullName: "Jane Smith",
    email: "jane.smith@example.com",
    role: "Developer",
    status: "Inactive",
    lastLogin: "2024-09-18T15:45:00Z",
  },
  {
    id: 3,
    fullName: "Mark Johnson",
    email: "mark.johnson@example.com",
    role: "Viewer",
    status: "Active",
    lastLogin: "2024-09-17T10:23:00Z",
  },
  {
    id: 4,
    fullName: "Emily Clark",
    email: "emily.clark@example.com",
    role: "Developer",
    status: "Active",
    lastLogin: "2024-09-20T08:45:00Z",
  },
  {
    id: 5,
    fullName: "Michael Johnson",
    email: "michael.johnson@example.com",
    role: "Viewer",
    status: "Inactive",
    lastLogin: "2024-09-17T10:12:00Z",
  },
  {
    id: 6,
    fullName: "Sophia Williams",
    email: "sophia.williams@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-09-18T14:22:00Z",
  },
  {
    id: 7,
    fullName: "James Brown",
    email: "james.brown@example.com",
    role: "Developer",
    status: "Inactive",
    lastLogin: "2024-09-19T09:30:00Z",
  },
  {
    id: 8,
    fullName: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    role: "Viewer",
    status: "Active",
    lastLogin: "2024-09-15T16:50:00Z",
  },
  {
    id: 9,
    fullName: "William Anderson",
    email: "william.anderson@example.com",
    role: "Admin",
    status: "Inactive",
    lastLogin: "2024-09-16T11:11:00Z",
  },
  {
    id: 10,
    fullName: "Emma Martinez",
    email: "emma.martinez@example.com",
    role: "Developer",
    status: "Active",
    lastLogin: "2024-09-20T07:30:00Z",
  },
];
